from urllib.parse import urlsplit, urlunsplit

from pydantic_settings import BaseSettings

DEFAULT_FRONTEND_ORIGIN = "https://gift-factory-1j7w.vercel.app"


class Settings(BaseSettings):
    anthropic_api_key: str = ""
    anthropic_base_url: str = "https://api.anthropic.com"
    deepseek_api_key: str = ""
    kimi_api_key: str = ""
    minimax_api_key: str = ""
    minimax_base_url: str = "https://api.minimaxi.com/v1"
    supabase_url: str
    supabase_service_key: str
    supabase_anon_key: str = ""
    supabase_storage_bucket: str = "gift-uploads"
    # Production is the safe default for asset URLs generated by Railway.
    # Local development can override this with FRONTEND_URL.
    frontend_url: str = DEFAULT_FRONTEND_ORIGIN

    class Config:
        env_file = ".env"

    @property
    def frontend_origin(self) -> str:
        raw = self.frontend_url.strip()
        parsed = urlsplit(raw)
        # A duplicated scheme in Railway variables can produce values such as
        # https://gift-factory-1j7w-git-https:/1.webp. Never emit those URLs.
        malformed = "://" in raw[8:] or parsed.netloc.endswith("-https:")
        if parsed.scheme in {"http", "https"} and parsed.netloc and not malformed:
            return urlunsplit((parsed.scheme, parsed.netloc, "", "", ""))
        return DEFAULT_FRONTEND_ORIGIN

settings = Settings()
